export const HEPL_DESK_API: string = `${this.HEPL_DESK}${HEPL_DESK_API_COMPLEMENTO}`;
export const HEPL_DESK_API_AUTH: string = `${this.HEPL_DESK}${HEPL_DESK_API_COMPLEMENTO}${HEPL_DESK_API_AUTH_COMPLEMENTO}`;
export const HEPL_DESK_API_USER: string = `${this.HEPL_DESK}${HEPL_DESK_API_COMPLEMENTO}${HEPL_DESK_API_USER_COMPLEMENTO}`;
export const HEPL_DESK_API_TICKET: string = `${this.HEPL_DESK}${HEPL_DESK_API_COMPLEMENTO}${HEPL_DESK_API_TICKET_COMPLEMENTO}`;
export const HEPL_DESK: string = 'https://helpdesk-web-service.herokuapp.com';
var HEPL_DESK_API_COMPLEMENTO: string = '/api';
var HEPL_DESK_API_AUTH_COMPLEMENTO: string = '/auth';
var HEPL_DESK_API_USER_COMPLEMENTO: string = '/user';
var HEPL_DESK_API_TICKET_COMPLEMENTO: string = '/ticket';